export const ARMOUR_MEMO = Object.freeze([
    ['Calcul par localisation', 'Chaque pièce ne protège que les zones indiquées : tête, corps, bras droit et gauche, jambe droite et gauche. Sur cette fiche, toute armure listée est prise en compte ; il n’y a pas d’état équipé ou déséquipé.'],
    ['Couches compatibles', 'Le cuir souple peut se porter sous une autre armure. Une armure Flexible, comme la maille, peut se porter sous une couche non flexible. Ainsi, cuir 1 PA + maille 2 PA + plates 2 PA donnent 5 PA sur une zone couverte par les trois pièces.'],
    ['Éviter les doubles comptes', 'Deux pièces d’une même couche ne doublent pas sa protection. La fiche retient la meilleure pièce par couche et par zone ; les autres restent dans la liste et le détail explique pourquoi elles ne comptent pas. Un bonus explicitement additionnel s’ajoute aux couches ; deux copies du même bonus ne le multiplient pas.'],
    ['Protection conditionnelle', 'Les PA affichés sont une valeur de référence avant les circonstances de l’attaque. Partielle : si le numéro de localisation est pair, les PA de cette pièce sont ignorés. Points faibles : un Critique avec une arme Empaleuse ignore les PA de cette pièce. Les autres couches restent à examiner séparément.'],
    ['Impénétrable', 'Un Coup critique causé par un jet pour toucher impair est ignoré. Cet atout ne donne pas de PA supplémentaires.'],
    ['Boucliers', 'Selon le PDF V5, opposer une attaque avec Esquive ou Corps à corps donne +1 DR avec un bouclier (sans cumul avec Défensive), puis ses PA si l’attaque touche. À partir de 2 PA, on peut opposer les tirs avec Esquive à toute portée. Un seul bouclier compte. Attaché au bras ou porté en bandoulière, il ne protège que la tête, le corps et le bras non directeur. Après avoir attaqué avec lui, on perd sa protection jusqu’au début du prochain tour. Son bonus reste donc séparé du total permanent. Les profils particuliers, comme le pavois posé, gardent leurs conditions et les mots clés de l’édition indiquée.'],
    ['Effets à appliquer en partie', 'Les talents, pénalités, effets magiques et autres mots clés sont des rappels : ils ne modifient pas automatiquement les compétences ou les dégâts de base. Les PA particuliers non chiffrés restent à préciser par le MJ.'],
]);
export const ARMOUR_MEMO_SOURCE = 'Cumul et défauts d’armure : Livre de base V5 EN v2, p. 306-307. Profils et mots clés : Aides de jeu de la campagne, édition retenue pour chaque entrée. Le calcul des couches identiques suit l’arbitrage de cette fiche.';
